apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-nodeaffinity-cache
spec:
  selector:
    matchLabels:
      name: redis-store
  replicas: 5
  template:
    metadata:
      labels:
        name: redis-store
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disk
                operator: In
                values:
                - ssd
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: disk
                operator: In
                values:
                - ssd
      containers:
      - name: "redis"
        image: "redis"