apiVersion: v1
kind: Service
metadata:
  name: webapp-helloworld
spec:
  # sessionAffinity: "None" # 会话模式
  type: NodePort
  ports:
  - port: 7788
    targetPort: 7777
    nodePort: 31281
  selector:
    name: webapp-helloworld