apiVersion: v1
kind: Service
metadata:
  name: webapp-arith-service
spec:
  # sessionAffinity: "ClientIP" # 会话模式
  type: NodePort
  ports:
  - port: 30001
    targetPort: 30001
    # nodePort: 30001
  selector:
    name: webapp-arith