apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-rc
  labels:
    name: helloworld
spec:
  replicas: 1
  selector:
    name: helloworld
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: helloworld
        image: soulmate/webapp-helloworld:latest
        imagePullPolicy: "Never"
        ports:
        - name: "http"
          containerPort: 7777
          protocol: "TCP"