apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    name: "webapp"
spec:
  replicas: 3
  selector:
    matchLabels:
      name: "webapp"
  template:
    metadata:
      labels:
        name: "webapp"
    spec:
      containers:
      - name: "webapp-container"
        image: "soulmate/webapp:latest"
        imagePullPolicy: "Never"
        ports:
        - name: "rpc-port"
          containerPort: 8888
          protocol: "TCP"