apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  # sessionAffinity: "ClientIP" # 会话模式
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 32123
  selector:
    name: webapp